### ISSUE TITLE
Should content of this repo be moved

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-net-samples#3]
Should we move this sample to https://github.com/Azure/azure-sdk-for-net/tree/master/samples
as we now have a place for end to end samples in the main repo or are there any plans for updating the content here? @KrzysztofCwalina @AlexGhiondea

**Comment by jongio** [comment]
yes, PR is here, closing this. https://github.com/Azure/azure-sdk-for-net/pull/17614
